### PR TITLE
avx-512 exponentiation patch, ported from openssl

### PR DESCRIPTION
**Pull request by pittma**

### CODE REVIEW

**Comment by pittma** [comment]
Added a test that focusses on the new mod_exp_consttime_x2 function, borrowing test cases from the mod_exp tests. You can run these tests like so (from inside the build directory):

```sh
build$ ninja && ./crypto_test --gtest_filter=BNTest.ModExp2TestVectors
```

The one case I've tried so far passes :/

**Comment by BadariP** [comment]
This is the test I have been using to debug.

It works without patch applied, but fails with the patch.

```sh
build$ ./crypto_test --gtest_filter=EVPTest.WycheproofRSAPKCS1Sign
```

**Comment by BadariP** [comment]
Failing code:

```c
int EVP_PKEY_sign(EVP_PKEY_CTX *ctx, uint8_t *sig, size_t *sig_len,
                  const uint8_t *digest, size_t digest_len) {
        int ret;
  if (!ctx || !ctx->pmeth || !ctx->pmeth->sign) {
    OPENSSL_PUT_ERROR(EVP, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE);
    fprintf(stderr, "sign1\n");
    return 0;
  }
  if (ctx->operation != EVP_PKEY_OP_SIGN) {
    OPENSSL_PUT_ERROR(EVP, EVP_R_OPERATON_NOT_INITIALIZED);
    fprintf(stderr, "sign2\n");
    return 0;
  }
  ret =  ctx->pmeth->sign(ctx, sig, sig_len, digest, digest_len);   // <<<<< returning 0
  if (ret == 0)
          mydebug(ctx);
  return ret;
}
```

**Comment by pittma** [comment]
> Failing code:
> 
> ```c
> int EVP_PKEY_sign(EVP_PKEY_CTX *ctx, uint8_t *sig, size_t *sig_len,
>                   const uint8_t *digest, size_t digest_len) {
>         int ret;
>   if (!ctx || !ctx->pmeth || !ctx->pmeth->sign) {
>     OPENSSL_PUT_ERROR(EVP, EVP_R_OPERATION_NOT_SUPPORTED_FOR_THIS_KEYTYPE);
>     fprintf(stderr, "sign1\n");
>     return 0;
>   }
>   if (ctx->operation != EVP_PKEY_OP_SIGN) {
>     OPENSSL_PUT_ERROR(EVP, EVP_R_OPERATON_NOT_INITIALIZED);
>     fprintf(stderr, "sign2\n");
>     return 0;
>   }
>   ret =  ctx->pmeth->sign(ctx, sig, sig_len, digest, digest_len);   // <<<<< returning 0
>   if (ret == 0)
>           mydebug(ctx);
>   return ret;
> }
> ```

What does `mydebug` look like?

**Comment by BadariP** [comment]
all the debug so far points to out buffer being "0"s..

Like I mentioned earlier, it seem to happen only when the buffer size is 256 (for 128 length works fine)

**Pull request closed without merging**
